### ISSUE TITLE
Not responding to route change

### ISSUE THREAD

**Issue by pm-consultancy** [socotecio/vue-datatable-url-sync#5]
I'm using it for a vue2 project.

But it looks like the watcher isn't responding to the route change.
when using the controls of the data table it works. But whenever I want to use back/forward. the data stays the same. 
No data requests
No option changes

**Comment by pm-consultancy** [comment]
I've just checked the demo, but that doesn't work either

**Comment by pm-consultancy** [comment]
possible fix was using: https://github.com/ambit-tsai/vue2-helpers

**Comment by AMontagu** [comment]
Hi @PaulMenheere 

We are watching the form, the options and the route.query. You indeed need to pass the route and the router as params to make it work. 

Indeed Vue2-helpers can be used to remove the route and router params.

Can you provide an example repository  ? Last time I checked it was working as on the video on the readme but something may be broke since.

**Comment by AMontagu** [comment]
Or at least a video with the example repository not working ? To be sure to understand your usage.

**Comment by pm-consultancy** [comment]
> 

I've used your repository and followed the steps (`npm install` & `npm serve`)

**Comment by AMontagu** [comment]
Okay. I will have time on monday to reset my local environment to verify that everything is working or fix the issue.

**Comment by AMontagu** [comment]
Ok so indeed context.root.$route was not dynamic. In my usage I was only use navigation when coming back from an other route not the same so it was working. 
I tried to make it work without installing vue2-helpers but I should have copy almost all their vue-router code. And as it is in the example it let the possibility to the user to use it or depending of their need.

Thank you for posting this issue and a potential fix.

PR: https://github.com/socotecio/vue-datatable-url-sync/pull/6
