### ISSUE TITLE
Vue 2.7

### ISSUE THREAD

**Issue by pm-consultancy** [socotecio/vue-datatable-url-sync#7]
Please make it compatible with vue 2.7 (no need for vue-demi)

**Comment by AMontagu** [comment]
Hi Paul.
Thanks for the suggestion. I have reserved some time on monday for that.

**Comment by AMontagu** [comment]
Hello I have make it work with vue 2.7 on the next branche.

you can install it with `npm i vue-datatable-url-sync@next`

There is one side effect about vue router wich doesn't actually support the useRouter and useRoute but working on it:
https://github.com/vuejs/vue-router/issues/3760
https://github.com/vuejs/vue-router/pull/3763

You can find an example of how make it work here: 
https://github.com/socotecio/vue-datatable-url-sync/blob/next/vue2.7-example/src/router/composable.js

Do not hesitate if you have any question and close your issue if its working as expected for you

**Comment by pm-consultancy** [comment]
I was just able to check it. But it's not working
Your example is changing the data, but not the url in the browser

If updated the component in my project, it doesn't work at all. (no loading data from the API)

**Comment by pm-consultancy** [comment]
I've narrowed down to the 'possible' culprit.

https://github.com/socotecio/vue-datatable-url-sync/blob/ea48ac8d973aa18ee1ff52874c739652a4eb4ea4/src/useDatatableUrlSync.ts#L105

Doesn't get fired at all. for some reason, it doesn't pick up on the changes on the options object

**Comment by pm-consultancy** [comment]
The watcher on the Form object https://github.com/socotecio/vue-datatable-url-sync/blob/ea48ac8d973aa18ee1ff52874c739652a4eb4ea4/src/useDatatableUrlSync.ts#L101 isn't working either

**Comment by pm-consultancy** [comment]
After some digging I found it
instead of using 
` import useDatatableUrlSync from 'vue-datatable-url-sync'`
You should use
` import useDatatableUrlSync from 'vue-datatable-url-sync/src/useDatatableUrlSync'`

**Comment by AMontagu** [comment]
Sorry for the late reply. 
This should not be an issue. Actually using vue-datatable-url-sync/src/useDatatableUrlSync instead of vue-datatable-url-sync will use the typescript file directly instead of its transpiled version: dist/vue-datatable-url-sync.esm.js.

This is working in local for me. can't say much about that. I will retry it now just to be sure.

**Comment by AMontagu** [comment]
Okay so you right. It is working in local when using directly the file but not the transpiled one that is used by default by npm.
Seem like there is an issue with webpack or vue 2.7. Will try to update it.

**Comment by AMontagu** [comment]
@PaulMenheere So vue-demi is still required for building the library for both vue2 and vue3.
We just needed an update of vue-demi to make it work correctly with vue 2.7. I merged everything in master. So the version 2.0.1 shoul be available without the "next" tag.
Tell me if you face an issue and close the issue if it's working for you

**Comment by AMontagu** [comment]
@PaulMenheere I am closing this. Do not hesitate to reopen it if needed
